---
- name: Download logFaces Client Tarball
  become: no
  get_url:
      url: "http://www.moonlit-software.com/logfaces/downloads/lfc.{{ logfaces_client_version }}.linux.gtk.x86_64.tar.gz "
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/logfaces-client-{{ logfaces_client_version }}.tar.gz"
      mode: 0444
  when: logfaces_client_install

- name: Uncompress logFaces Client Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/logfaces-client-{{ logfaces_client_version }}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_software_directory}}/logFacesClient/about.html"
  when: logfaces_client_install

- name: Create Softlink To logFaces Client JRE
  become: no
  file:
      src: "{{jdk_destination}}//zulu{{jdk_azul_jdk_build}}-jdk{{jdk_azul_jdk_version}}-linux_x64/jre"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/logFacesClient/jre"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
# when: logfaces_client_install
  when: false

- name: Create Softlink To logFaces Client
  become: no
  file:
      src: "{{ansible_user_dir}}/{{base_software_directory}}/logFacesClient"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/logfaces"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: logfaces_client_install

- name: Create Desktop Icon For logFaces Client
  become: no
  template:
      src: "templates/logfaces.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/logfaces.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0755
  when: logfaces_client_install

